### ISSUE TITLE
Relay URL is not normalize

### ISSUE THREAD

**Issue by reyamir** [SnowCait/nostter#1232]
**Issue**:
Relay URL is not normalize, so Nostter is connecting two same relay if `/` is present in the URL

```
wss://relay.damus.io
wss://relay.damus.io/
```

<img width="618" alt="image" src="https://github.com/SnowCait/nostter/assets/123083837/aefdfedc-f17c-4511-aafe-1f38c437daf2">

**Comment by SnowCait** [comment]
It will be fixed by https://github.com/penpenpng/rx-nostr/issues/125.

**Comment by SnowCait** [comment]
This issue was fixed at #1319.
If not, please let me know.
