### ISSUE TITLE
Nostr Profile Page Unrechable if Verification Server is offline

### ISSUE THREAD

**Issue by dwarf-king-hreidmar** [SnowCait/nostter#1350]
Setup:
Nostter Web Client
nos2x-fox
lighttpd server hosting my .well-known/nostr.json file for NIP-05

What happened:
- If my lighttpd server is down https://dkh.nidavellir.net and I try to access my profile page (https://nostter.app/dkh.nidavellir.net) I get the "Not found or something is wrong" message.
- Nothing loads there but I can see my profile in other clients.
- I can still see my messages.

What I would expect to happen:
- Page still loads
- Verified badge is removed
- All the other portions of the profile page still function.

Let me know if I can help troubleshoot

**Comment by SnowCait** [comment]
When you access `https://nostter.app/dkh.nidavellir.net`, nostter (Nostr) works like this:
1. Fetch nostr.json from `https://dkh.nidavellir.net/.well-known/nostr.json?name=_`
2. Find your pubkey from nostr.json
3. Show profile page of the pubkey

If 1. failed, 2. and 3. doesn't work.
The "Not found or something is wrong" message being displayed is correct behavior when `https://dkh.nidavellir.net/` is down.

I can cache nostr.json but it's not forever.
If you want to access your page when your sever is down, please use nprofile or npub which contain pubkey. (They can skip 1. and 2.)
https://nostter.app/nprofile1qqs8kmthcyq3emz2upzfrramhn0wr50c4x3hwh7eck2llv7vv5kxcvsmjn4xc

**Comment by dwarf-king-hreidmar** [comment]
Ah, I understand how this works now. Thanks so much for helping my understand :)
