### ISSUE TITLE
Timeline always holds 50 items with muted items, creating large empty space

### ISSUE THREAD

**Issue by MaySoMusician** [SnowCait/nostter#1380]
`VirtualScroll` (used in Timeline) always holds 50 items, and it looks like we pass the items to it regardless of whether each item is muted or not. This results in the timeline having a lot of empty space if there's a lot of muted items.

https://github.com/user-attachments/assets/90609247-3e66-4fc7-b938-9ef4fdc10567

We should filter out the muted items before passing to `VirtualScroll`

**Comment by MaySoMusician** [comment]
I'm giving a shot...

**Comment by SnowCait** [comment]
Relates to #1283
