### ISSUE TITLE
テキストエリア外をタップするとテキストエリアが閉じてしまう

### ISSUE THREAD

**Issue by koteitan** [SnowCait/nostter#157]
テキストエリア外をタップすると編集画面が閉じてしまいます

iPhone では、テキストエリア外にカーソルを移動する、選択する、の動作のためにテキストエリアをドラッグする必要がありますが、テキストエリアが狭いので誤タップの確率が非常に高く、閉じる動作が結構頻繁に発動してしまいます

対策案：
(対策案) 投稿内容編集画面に×ボタンを設けて、明示的にそれを押した時のみ閉じる

**Comment by SnowCait** [comment]
PC だとダイアログ外をクリックしたときに閉じれた方が便利なので PC とスマホで UI を変える予定です。
方針は未定。
- ×ボタン
- 投稿専用画面
- その他

**Comment by SnowCait** [comment]
書きかけの場合は確認ダイアログを出すようにしました。 #1212
