### ISSUE TITLE
起動時にボタンが全部グレーアウトしてしまう

### ISSUE THREAD

**Issue by Memory-of-Snow** [SnowCait/nostter#263]
<img width="470" alt="スクリーンショット 2023-05-12 204436" src="https://github.com/SnowCait/nostter/assets/98633948/4766ada3-3874-4f1a-a3e0-841b5bae991f">

今日、アクセス時にこのような画面のままということがありました。
Windows10上のGoogleChrome113.0.5672.93です。
その時のコンソールのログが、以下になります。

<img width="269" alt="スクリーンショット 2023-05-12 204106" src="https://github.com/SnowCait/nostter/assets/98633948/2abf21e1-0342-4bb6-b1bd-214301c132eb">

**Comment by SnowCait** [comment]
`nostr-provider.js` は拡張機能 (nos2x?) のコードのようなのでクライアント側で対応するのは難しそう。

**Comment by Memory-of-Snow** [comment]
わかりました。

**Comment by SnowCait** [comment]
Relates to #160 
エラーになったときに再度ボタンを押せるようにする。
