### ISSUE TITLE
Top page

### ISSUE THREAD

**Issue by SnowCait** [SnowCait/nostter#535]
## ~~Description~~

~~Nostr web app.~~
~~What is Nostr?~~

## Pros

- Familiar Design
  - 使い慣れたデザイン
- Full-featured Timeline
  - 多機能なタイムライン
  - Needless to see mutiple timelines
  - 時系列
- Secure Login
  - 安全なログイン
- PWA
- Developer friendly
  - 開発者フレンドリー
- About Nostr
  - https://welcome.nostr-jp.org/

**Comment by studiokaiji** [comment]
文字数制限がないことや、アカウントが削除されない(これに関してはもうすこし濁した表現の方がいいかも)等のユーザーにとっての特にTwitterと比べた時の利点を書いておくといいと思います！

**Comment by SnowCait** [comment]
https://nostter.vercel.app/nevent1qqsdf9jjmwwn2c32l3d6qgfsjephd3u6975qf9q4xhzmwqzv064fnjcyffzrf
https://nostter.vercel.app/nevent1qqsyr050zhaz26q2x2qchpk6d52r730cfeytpg7ffgnu5uw0qlxry0chspmu7

**Comment by SnowCait** [comment]
https://nostter.vercel.app/nevent1qqszf9mnr3admh47hx8mjwj8jfe02ehfxjtsv7662fjdc4lj4g683pgtrl5y0

>- 管理者がいない
>- BAN されない
>- 自分で接続先を選べる

https://nostter.vercel.app/nevent1qqsgp6p0snuc90yuy5h7gn5wyk66rk7vxyav5jct85505esl0wwp0gc74qlrm

>- ID のかぶりを気にしなくていい

https://nostter.vercel.app/nevent1qqsq40vv6qtkk5wj9kqpl9pyy498s8flvpm4tr3e79jmcut7qdsvcws3ahd4t

>- 消せない（と思ってほしい）
>- 鍵垢できない
>- 相手を縛ることもできないので完全なブロックはできない
>
>とかはどっかで教えてあげてほし

https://nostter.vercel.app/nevent1qqs9mh08dwvqxmf47kfczpqyau3f0st2vm58cyduqz45c770cex6yjguajjp3

>- 個人情報を取られない

https://nostter.vercel.app/nevent1qqs0n39agq0e7wxfffdn7mntldgl2jygufm4z3h8f926uu8al86m6hq56qmw3

>「鍵」ひとつで使える、縛られない SNS

**Comment by SnowCait** [comment]
#702
