### ISSUE TITLE
Relay is fetched repeatedly while navigating the site

### ISSUE THREAD

**Issue by alexgleason** [SnowCait/nostter#964]
I found a lot of requests from nostter.app in my Nginx logs. It is essentially DoSing relays while people use it. You can see it fetching the same relay many times just while navigating the app:

![image](https://github.com/SnowCait/nostter/assets/3639540/caa8788c-20ec-4921-ad48-9806a849527e)

**Comment by SnowCait** [comment]
@alexgleason 
Thank you for reporting.
I would like to confirm one thing.
Do you mean HTTPS (Type: fetch) request?

**Comment by alexgleason** [comment]
Yep. It's a GET to `/`

**Comment by SnowCait** [comment]
This is a library bug and I sent a PR. (Library makes NIP-11 requests automatically.)
I'll update library version after merged.

**Comment by Yonle** [comment]
Some notice, I noticed similiar traffic that not also including GET request, But also an websocket connection and then disconnected, which then connects again.

Probably has some relation to this client.

**Comment by alexgleason** [comment]
Thank you!
